### ISSUE TITLE
self - attention Pooling for Efficient Deep Learning code

### ISSUE THREAD

**Issue by ahdxwg** [sysuimg/Local-Patch-Network-with-Global-Attention#3]
你好，我对您的论文self - attention Pooling for Efficient Deep Learning非常感兴趣，但是您论文的代码链接已经失效了，您能分享一下代码吗?非常感谢!

**Comment by C-Fun** [comment]
你好，这个项目的代码链接：https://github.com/C-Fun/Self-Attentive-Pooling-for-Efficient-Deep-Learning
如有其他问题请直接联系我的邮箱：fchen905@usc.edu
